; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;vscode: Shift + Alt + B


#define MyAppName "PCBogota Cleaner Script"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "PCBogota"
#define MyAppURL "https://www.github.com/PCBogota"
#define MyAppExeName "Limpiar.cmd"

#define AppFilesPath "D:\devProjects\Clean temps"
#define AssetsPath AppFilesPath + "\installer\assets"
#define BuildPath AppFilesPath + "\build"

#define Lastpage "wpSelectTasks"


#define MultiImage(WizzImage) \
  AssetsPath + "\png_" + WizzImage + "_dpi-100.png," + \
  AssetsPath + "\png_" + WizzImage + "_dpi-125.png," + \
  AssetsPath + "\png_" + WizzImage + "_dpi-150.png," + \
  AssetsPath + "\png_" + WizzImage + "_dpi-175.png," + \
  AssetsPath + "\png_" + WizzImage + "_dpi-200.png," + \
  AssetsPath + "\png_" + WizzImage + "_dpi-225.png," + \
  AssetsPath + "\png_" + WizzImage + "_dpi-250.png"


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppCopyright=Copyright (C) 2026 PCBogota.
AppId={{911E6179-DC8E-4D99-9A42-3AF9238B2AB9}
AppName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppVersion={#MyAppVersion}
ArchitecturesInstallIn64BitMode=x64compatible
Compression=lzma
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
DisableReadyMemo=yes
DisableReadyPage=yes
DisableWelcomePage=no
LicenseFile=License.txt
OutputBaseFilename=Setup {#MyAppName} v{#MyAppVersion}
OutputDir={#AppFilesPath}\Output
PrivilegesRequired=admin
SetupIconFile="{#BuildPath}\PCBCleaner.ico"
SolidCompression=yes
WizardStyle=modern dynamic windows11

;;;BRANDING IMAGES
; WizardImageFile DPI: 100%=202x386, 125%=269x515, 150%=336x643, 175%=403x772, 200%=430x824, 225%=498x953, 250%=534x1022
WizardImageFile={#MultiImage("WizardImage")}
WizardImageFileDynamicDark={#MultiImage("WizardImage")}

;WizardSmallImageFile DPI: 100%=58x58, 125%=77x77, 150%=97x97, 175%=116x116, 200%=124x124, 225%=143x143, 250%=159x159
WizardSmallImageFile={#MultiImage("WizardSmallImage")}
WizardSmallImageFileDynamicDark={#MultiImage("WizardSmallImage")}

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
;Checkbox en la sección de tareas adicionales
Name: "registrar_tarea"; Description: "Programar limpieza automática al inicio de sesión"; GroupDescription: "Configuración de Automatización:";

[Files]
Source: "{#BuildPath}\BleachBit-portable\*"; DestDir: "{app}\BleachBit-portable\"; Flags: ignoreversion recursesubdirs
Source: "{#BuildPath}\CleanTemps.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildPath}\IniData.psd1"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildPath}\Limpiar.cmd"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildPath}\PCBCleaner.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "license.txt"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Limpieza Manual"; Filename: "{app}\Limpiar.cmd"; IconFilename: "{app}\PCBCleaner.ico"
Name: "{group}\PCB Script License"; Filename: "{app}\license.txt";
Name: "{commondesktop}\Limpieza Manual"; Filename: "{app}\Limpiar.cmd"; IconFilename: "{app}\PCBCleaner.ico"

[Run]
; Ejecuta SI el checkbox "registrar_tarea" está marcado
Filename: "powershell.exe"; \
Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\CleanTemps.ps1"" -Install -Auto"; \
Flags: runhidden; \
StatusMsg: "Registrando Tarea Programada de mantenimiento..."; \
Check: WizardIsTaskSelected('registrar_tarea')

[Code]
procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID in [{#lastPage}, wpReady] then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonInstall)
  else if CurPageID = wpFinished then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonFinish)
  else
    WizardForm.NextButton.Caption := SetupMessage(msgButtonNext);
end;
