; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;vscode: Shift + Alt + B


#define MyAppName "PCBogota Cleaner Script"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "PCBogota"
#define MyAppURL "https://www.github.com/PCBogota"
#define MyAppExeName "Limpiar.cmd"

#define AppFilesPath "D:\devProjects\Clean temps"
#define AssetsPath AppFilesPath + "\assets\common"
#define EditionPath AppFilesPath + "\Editions\Basic"
#define CorePath AppFilesPath + "\core"

#define Lastpage "wpSelectTasks"


#define MultiImage(WizzImage) \
  AssetsPath + "\wizzard_branding\png_" + WizzImage + "_dpi-100.png," + \
  AssetsPath + "\wizzard_branding\png_" + WizzImage + "_dpi-125.png," + \
  AssetsPath + "\wizzard_branding\png_" + WizzImage + "_dpi-150.png," + \
  AssetsPath + "\wizzard_branding\png_" + WizzImage + "_dpi-175.png," + \
  AssetsPath + "\wizzard_branding\png_" + WizzImage + "_dpi-200.png," + \
  AssetsPath + "\wizzard_branding\png_" + WizzImage + "_dpi-225.png," + \
  AssetsPath + "\wizzard_branding\png_" + WizzImage + "_dpi-250.png"


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppCopyright=Copyright (C) 2026 PCBogota.
AppId={{911E6179-DC8E-4D99-9A42-3AF9238B2AB9}
AppName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppVersion={#MyAppVersion}
ArchitecturesInstallIn64BitMode=x64compatible
Compression=lzma
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
DisableReadyMemo=yes
DisableReadyPage=yes
DisableWelcomePage=no
LicenseFile=License.txt
OutputBaseFilename=Setup {#MyAppName} v{#MyAppVersion}
OutputDir={#AppFilesPath}\Output
PrivilegesRequired=admin
SetupIconFile="{#EditionPath}\PCBCleaner.ico"
SolidCompression=yes
WizardStyle=modern dynamic windows11

;;;BRANDING IMAGES
; WizardImageFile DPI: 100%=202x386, 125%=269x515, 150%=336x643, 175%=403x772, 200%=430x824, 225%=498x953, 250%=534x1022
WizardImageFile={#MultiImage("WizardImage")}
WizardImageFileDynamicDark={#MultiImage("WizardImage")}

;WizardSmallImageFile DPI: 100%=58x58, 125%=77x77, 150%=97x97, 175%=116x116, 200%=124x124, 225%=143x143, 250%=159x159
WizardSmallImageFile={#MultiImage("WizardSmallImage")}
WizardSmallImageFileDynamicDark={#MultiImage("WizardSmallImage")}

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
;Checkbox en la sección de tareas adicionales
Name: "registrar_tarea"; Description: "Programar limpieza automática al inicio de sesión"; GroupDescription: "Configuración de Automatización:";
Name: "disable_hibernation"; Description: "Desactivar la hibernación del sistema"; GroupDescription: "Configuración de Automatización:";


[Files]
;BleachBit is not required before installation
;; Source: "{#EditionPath}\BleachBit-portable\*"; DestDir: "{app}\BleachBit-portable\"; Flags: ignoreversion recursesubdirs
Source: "{#CorePath}\basic-clean.ps1.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#CorePath}\IniData.psd1"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#CorePath}\Faltan archivos de core.psd1"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#EditionPath}\Limpiar.cmd"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#EditionPath}\Start-BasicClean.cmd"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#AssetsPath}\icon\PCBCleaner.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "license.txt"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Limpieza Manual"; Filename: "{app}\Limpiar.cmd"; IconFilename: "{app}\PCBCleaner.ico"
Name: "{group}\PCB Script License"; Filename: "{app}\license.txt";
Name: "{commondesktop}\Limpieza Manual"; Filename: "{app}\Limpiar.cmd"; IconFilename: "{app}\PCBCleaner.ico"

[Run]
; Ejecuta SI el checkbox "registrar_tarea" está marcado
Filename: "powershell.exe"; \
Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\CleanTemps.ps1"" -Install -Auto {code:GetTaskParam}"; \
Flags: runhidden; \
StatusMsg: "Registrando Tarea Programada de mantenimiento..."; \
Check: WizardIsTaskSelected('registrar_tarea')

; Nueva entrada: escribe en el registro si se marcó la hibernación
Filename: "reg.exe"; \
Parameters: "ADD ""HKLM\Software\PCBogota\PCB Cleaner"" /v DisableHibernation /t REG_DWORD /d 1 /f"; \
Flags: runhidden; \
Check: WizardIsTaskSelected('disable_hibernate')

; Opcional: si NO se marcó, asegurar que la clave tenga 0
Filename: "reg.exe"; \
Parameters: "DELETE ""HKLM\Software\PCBogota\PCB Cleaner"" /v HibernateDisabled /f"; \
Flags: runhidden; \
Check: not WizardIsTaskSelected('disable_hibernation')

[Code]
procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID in [{#lastPage}, wpReady] then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonInstall)
  else if CurPageID = wpFinished then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonFinish)
  else
    WizardForm.NextButton.Caption := SetupMessage(msgButtonNext);
end;

function GetTaskParam(Param: String): String;
begin
  if WizardIsTaskSelected('registrar_tarea') then
    Result := '-CreateTask'
  else
    Result := '';
end;
