; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;vscode: Shift + Alt + B


#define MyAppName "PCBogota Cleaner Script"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "PCBogota"
#define MyAppURL "https://www.github.com/PCBogota"
#define MyAppExeName "Limpiar.cmd"

; Main paths
#define AppFilesPath "D:\devProjects\Clean temps"
#define CorePath AppFilesPath + "\core"
#define EditionPath AppFilesPath + "\Editions\Basic"

; Assets paths
#define CommonAssets AppFilesPath + "\Assets\Common"
#define CommonWizzardAssets CommonAssets + "\wizzard_branding"
; #define EditionAssets AppFilesPath + "\Assets\<Edition>"
; #define EditionWizzardAssets CommonAssets + "\wizzard_branding"

; Powershell clean script file name
#define CleanScript "Start-BasicClean.ps1"

#define Lastpage "wpSelectTasks"

; functions
#define GetDPIImageList(BaseFolder, ImageName) \
  BaseFolder + "\png_" + ImageName + "_dpi-100.png," + \
  BaseFolder + "\png_" + ImageName + "_dpi-125.png," + \
  BaseFolder + "\png_" + ImageName + "_dpi-150.png," + \
  BaseFolder + "\png_" + ImageName + "_dpi-175.png," + \
  BaseFolder + "\png_" + ImageName + "_dpi-200.png," + \
  BaseFolder + "\png_" + ImageName + "_dpi-225.png," + \
  BaseFolder + "\png_" + ImageName + "_dpi-250.png"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for
; other applications, but change for other editions.
AppCopyright=Copyright (C) 2026 PCBogota.
AppId={{911E6179-DC8E-4D99-9A42-3AF9238B2AB9}
AppName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppVersion={#MyAppVersion}
ArchitecturesInstallIn64BitMode=x64compatible
Compression=lzma
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
DisableReadyMemo=yes
DisableReadyPage=yes
DisableWelcomePage=no
LicenseFile={#AppFilesPath}\installer\license.txt
OutputBaseFilename=Setup {#MyAppName} v{#MyAppVersion}
OutputDir={#AppFilesPath}\output
PrivilegesRequired=admin
SetupIconFile="{#CommonAssets}\Icon\PCBCleaner.ico"
SolidCompression=yes
WizardStyle=modern dynamic windows11

;;;BRANDING IMAGES
; WizardImageFile DPI: 100%=202x386, 125%=269x515, 150%=336x643, 175%=403x772, 200%=430x824, 225%=498x953, 250%=534x1022

; For basic edition
WizardImageFile={#GetDPIImageList(CommonWizzardAssets, "WizardImage")}
WizardImageFileDynamicDark={#GetDPIImageList(CommonWizzardAssets, "WizardImage")}

; For other editions comment the above two lines an use these instead:
; WizardImageFile={#GetDPIImageList(EditionWizzardAssets, "WizardImage")}
; WizardImageFileDynamicDark={#GetDPIImageList(EditionWizzardAssets, "WizardImage")}


;WizardSmallImageFile DPI: 100%=58x58, 125%=77x77, 150%=97x97, 175%=116x116, 200%=124x124, 225%=143x143, 250%=159x159
; Small Image is common for all editions
WizardSmallImageFile={#GetDPIImageList(CommonWizzardAssets, "WizardSmallImage")}
WizardSmallImageFileDynamicDark={#GetDPIImageList(CommonWizzardAssets, "WizardSmallImage")}

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
;Checkbox en la sección de tareas adicionales
Name: "registrar_tarea"; Description: "Programar limpieza automática al inicio de sesión"; GroupDescription: "Configuración de Automatización:";
Name: "disable_hibernation"; Description: "Forzar desactivar hibernación del sistema"; GroupDescription: "Configuración de Automatización:";

[Files]
;BleachBit is not required before installation
;; Source: "{#EditionPath}\BleachBit-portable\*"; DestDir: "{app}\BleachBit-portable\"; Flags: ignoreversion recursesubdirs

; Every file of Core logic
Source: "{#CorePath}\*"; DestDir: "{app}\Core"; Flags: createallsubdirs ignoreversion recursesubdirs

; Required graphic assets
Source: "{#CommonAssets}\Icon\*.png"; DestDir: "{app}\Assets\Icon"; Flags: createallsubdirs ignoreversion recursesubdirs
Source: "{#CommonAssets}\Icon\PCBCleaner.ico"; DestDir: "{app}\Assets\Icon"; Flags: ignoreversion

; Edition launchers
Source: "{#EditionPath}\*"; DestDir: "{app}"; Flags: createallsubdirs ignoreversion recursesubdirs

; Other files
Source: "{#AppFilesPath}\installer\license.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#AppFilesPath}\README.md"; DestDir: "{app}"; Flags: ignoreversion


[Icons]
Name: "{group}\Limpieza Manual"; Filename: "{app}\Limpiar.cmd"; IconFilename: "{app}\Assets\Icon\PCBCleaner.ico"
Name: "{group}\PCB Script License"; Filename: "{app}\license.txt";
Name: "{group}\Ver notas en línea"; Filename: "https://github.com/pcbogota/pcb-cleaner";
Name: "{commondesktop}\Limpieza Manual"; Filename: "{app}\Limpiar.cmd"; IconFilename: "{app}\Assets\Icon\PCBCleaner.ico"

[Run]
Filename: "powershell.exe"; \
Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\{#CleanScript}"" -Install -Auto {code:GetTaskParam} {code:GetHibernate}"; \
Flags: runhidden; \
StatusMsg: "Configurando el limpiador. Espera..."

[Code]
procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID in [{#lastPage}, wpReady] then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonInstall)
  else if CurPageID = wpFinished then
    WizardForm.NextButton.Caption := SetupMessage(msgButtonFinish)
  else
    WizardForm.NextButton.Caption := SetupMessage(msgButtonNext);
end;

function GetTaskParam(Param: String): String;
begin
  if WizardIsTaskSelected('registrar_tarea') then
    Result := '-Task'
  else
    Result := '';
end;

function GetHibernate(Param: String): String;
begin
  if WizardIsTaskSelected('disable_hibernation') then
    Result := '-DisableHibernation'
  else
    Result := '';
end;
